language: python
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get update -qq
  - sudo make install
  - sudo python setup.py install
  - 
script: unittest

notifications:
  email:
    recipients:
      - kensuke.mit@gmail.com
    on_success: always
    on_failure: always